# Generated by Django 2.2.5 on 2019-10-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191017_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('kg', 'Kg'), ('un', 'Un'), ('pct', 'Pct')], default='Un', max_length=5),
        ),
    ]
