# Generated by Django 2.2.5 on 2019-10-24 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191024_2010'),
        ('frente_de_caixa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensDeVenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Produto')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Servico')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='servico',
        ),
        migrations.DeleteModel(
            name='Itens_Vendidos',
        ),
        migrations.DeleteModel(
            name='Vendas',
        ),
        migrations.AddField(
            model_name='itensdevenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frente_de_caixa.Venda'),
        ),
    ]
